DROP SCHEMA HR_POLICIES_DB.DEV;
DROP DATABASE HR_POLICIES_DB;

DROP WAREHOUSE CORTEX_DEMO_WH;

DROP SECURITY INTEGRATION entra_id_cortex_agents_integration ;
DROP USER TEAMS_DEEPTI;
DROP ROLE TEAMS_CORTEX_AGENT_USER_ROLE; 