--Query to check warehouse cost PER DAY

WITH PARAMETERS AS (
    SELECT 3.00::NUMBER(10,2) AS USD_PER_CREDIT
)
SELECT
    DATE_TRUNC('DAY', START_TIME) AS USAGE_DATE,
    WAREHOUSE_NAME,
    SUM(CREDITS_USED) AS CREDITS_USED,
    ROUND(SUM(CREDITS_USED) * MAX(USD_PER_CREDIT), 2) AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
CROSS JOIN PARAMETERS
WHERE WAREHOUSE_NAME = 'CORTEX_DEMO_WH'
GROUP BY 1, 2;

--Monthly threshold check

WITH PARAMETERS AS (
    SELECT 3.00::NUMBER(10,2) AS USD_PER_CREDIT
)
SELECT
    DATE_TRUNC('MONTH', START_TIME) AS MONTH_START,
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 2) AS CREDITS_USED,
    ROUND(SUM(CREDITS_USED) * MAX(USD_PER_CREDIT), 2) AS ESTIMATED_COST_USD,
    IFF(
        SUM(CREDITS_USED) * MAX(USD_PER_CREDIT) >= 50,
        'LIMIT EXCEEDED',
        IFF(
            SUM(CREDITS_USED) * MAX(USD_PER_CREDIT) >= 40,
            'WARNING - ABOVE 80%',
            'WITHIN LIMIT'
        )
    ) AS COST_STATUS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
CROSS JOIN PARAMETERS
WHERE WAREHOUSE_NAME = 'CORTEX_DEMO_WH'
GROUP BY 1, 2;


--TOTAL WAREHOUSE COST
WITH PARAMETERS AS (
    SELECT 3.00::NUMBER(10,2) AS USD_PER_CREDIT
)
SELECT
    WAREHOUSE_NAME,
    ROUND(SUM(CREDITS_USED), 4) AS TOTAL_CREDITS_USED,
    ROUND(SUM(CREDITS_USED) * MAX(USD_PER_CREDIT), 2) AS ESTIMATED_TOTAL_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
CROSS JOIN PARAMETERS
WHERE WAREHOUSE_NAME = 'CORTEX_DEMO_WH'
GROUP BY WAREHOUSE_NAME;