--Resource Monitor for monitoring warehouse cost
CREATE OR REPLACE RESOURCE MONITOR CORTEX_DEMO_COST_MONITOR
  WITH CREDIT_QUOTA = 30
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 80 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;


--Attach RM to the the warehouse
ALTER WAREHOUSE CORTEX_DEMO_WH
  SET RESOURCE_MONITOR = CORTEX_DEMO_COST_MONITOR;